"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowRight, Check, ChevronRight, Copy, Menu, Minus, Package, PawPrint, Plus, ShoppingBag, SlidersHorizontal, X } from "lucide-react";
type Category = "Todos" | "Perros" | "Gatos" | "Snacks";
type Product = { id: string; name: string; category: Category; line: string; weight: string; image: string; note: string; color: string };
const products: Product[] = [
 {id:"dog-adult",name:"El plato de todos los días",category:"Perros",line:"Alimento seco · Adultos",weight:"15 kg",image:"/images/dog-food-v2.webp",note:"Una referencia para la alimentación diaria de perros adultos. La ficha comercial puede incluir composición, análisis y recomendaciones del fabricante.",color:"green"},
 {id:"cat-adult",name:"Para pequeños exigentes",category:"Gatos",line:"Alimento seco · Adultos",weight:"7,5 kg",image:"/images/cat-food-v2.webp",note:"Una referencia para la línea felina, con espacio para presentar etapa de vida, formatos y ficha técnica del fabricante.",color:"rust"},
 {id:"treat-bones",name:"Un premio bien merecido",category:"Snacks",line:"Galletas · Perros",weight:"500 g",image:"/images/treats-v2.webp",note:"Una referencia para snacks y premios. Un formato pequeño para complementar la selección de alimentos.",color:"lime"},
 {id:"dog-small",name:"Grande en lo que importa",category:"Perros",line:"Alimento seco · Razas pequeñas",weight:"3 kg",image:"/images/dog-food-v2.webp",note:"Una presentación compacta para explorar una línea de alimentos para perros de razas pequeñas.",color:"green"},
 {id:"cat-small",name:"Su rincón favorito",category:"Gatos",line:"Alimento seco · Formato pequeño",weight:"1,5 kg",image:"/images/cat-food-v2.webp",note:"Una referencia de formato pequeño para construir un surtido con distintas presentaciones.",color:"rust"},
 {id:"treat-pack",name:"Más momentos felices",category:"Snacks",line:"Galletas · Caja de 6 unidades",weight:"6 × 500 g",image:"/images/treats-v2.webp",note:"Una presentación por caja para demostrar cómo solicitar productos por volumen, sin pasar por un pago online.",color:"lime"}
];
const filters: Category[] = ["Todos","Perros","Gatos","Snacks"];
export default function Home(){
 const [filter,setFilter]=useState<Category>("Todos"),[selection,setSelection]=useState<Record<string,number>>({}),[detail,setDetail]=useState<Product|null>(null),[quoteOpen,setQuoteOpen]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[notice,setNotice]=useState(""),[copied,setCopied]=useState(false),[request,setRequest]=useState("");
 const detailRef=useRef<HTMLDialogElement>(null),quoteRef=useRef<HTMLDialogElement>(null);
 const count=Object.values(selection).reduce((a,b)=>a+b,0),selected=products.filter(p=>selection[p.id]>0);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(n=>observer.observe(n));return()=>observer.disconnect()},[]);
 useEffect(()=>{const d=detailRef.current;if(detail&&d&&!d.open)d.showModal();else if(!detail&&d?.open)d.close()},[detail]);
 useEffect(()=>{const d=quoteRef.current;if(quoteOpen&&d&&!d.open)d.showModal();else if(!quoteOpen&&d?.open)d.close()},[quoteOpen]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(""),3500);return()=>clearTimeout(t)},[notice]);
 function quantity(id:string,delta:number){setSelection(s=>({...s,[id]:Math.max(0,Math.min(99,(s[id]||0)+delta))}));setRequest("");setCopied(false)}
 function add(p:Product){quantity(p.id,1);setNotice(`${p.name} agregado a tu selección`)}
 function openQuote(){setDetail(null);setQuoteOpen(true);setRequest("");setCopied(false)}
 function prepare(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const lines=selected.map(p=>`• ${p.name} — ${p.weight}: ${selection[p.id]} unidades`).join("\n");setRequest(`Hola Nicolás, probé la demo de Safari Pez y quisiera conversar sobre una web similar.\n\nNombre: ${String(d.get("name")).trim()}\nNegocio: ${String(d.get("business")).trim()}\nComuna: ${String(d.get("city")).trim()}\n\nSelección de ejemplo:\n${lines}\n\nEsto es una consulta sobre desarrollo web, no una compra de alimentos.`);setCopied(false)}
 async function copy(){try{await navigator.clipboard.writeText(request);setCopied(true)}catch{setNotice("No se pudo copiar. Puedes seleccionar el texto de la solicitud.")}}
 return <>
 <a className="skip-link" href="#contenido">Saltar al contenido</a>
 <div className="portfolio-strip"><span>Proyecto de Nicolás Cortez <span className="strip-divider">/</span> Catálogo B2B interactivo</span><a href="https://nicolas-cortez.vercel.app">Volver al portafolio <ArrowRight size={13}/></a></div>
 <header className="site-header"><a className="brand" href="#inicio" aria-label="Safari Pez, inicio"><PawPrint className="brand-icon" size={32}/><span>safari<span className="brand-dot">.</span>pez<small>ALIMENTOS PARA MASCOTAS</small></span></a><nav aria-label="Navegación principal" className={mobileOpen?"nav-links is-open":"nav-links"}><a onClick={()=>setMobileOpen(false)} href="#catalogo">El catálogo</a><a onClick={()=>setMobileOpen(false)} href="#negocios">Para tu negocio</a><a onClick={()=>setMobileOpen(false)} href="#nosotros">Nuestra idea</a></nav><div className="header-actions"><button className="selection-button" onClick={openQuote} aria-label={`Ver selección, ${count} unidades`}><ShoppingBag size={18}/><span className="selection-label">Mi selección</span><span className="selection-count">{count}</span></button><button className="mobile-toggle" onClick={()=>setMobileOpen(!mobileOpen)} aria-label={mobileOpen?"Cerrar menú":"Abrir menú"} aria-expanded={mobileOpen}>{mobileOpen?<X/>:<Menu/>}</button></div></header>
 <main id="contenido">
 <section id="inicio" className="hero"><div className="hero-copy"><p className="eyebrow light"><span/> NUTRICIÓN ANIMAL · DISTRIBUCIÓN PARA NEGOCIOS</p><h1>Buena comida.<br/>Mejores <em>colitas.</em></h1><p className="hero-description">Alimentos y snacks para perros y gatos.<br/>Un catálogo pensado para abastecer tu petshop, veterinaria o comercio.</p><div className="hero-actions"><a className="button button-lime" href="#catalogo">Explorar el catálogo <ArrowRight size={19}/></a><a className="hero-secondary" href="#negocios">Tengo un negocio <ChevronRight size={17}/></a></div><div className="hero-caption"><span className="caption-line"/><p>Selecciona productos. Define cantidades.<br/>Arma una solicitud a tu medida.</p></div></div><div className="hero-visual"><img className="hero-image" src="/images/hero-pets-v2.webp" alt="Perro golden retriever y gato junto a un envase de alimento y un plato con croquetas" width="1536" height="1024" fetchPriority="high"/><div className="hero-tag"><PawPrint size={21}/><span>Para quienes<br/><b>nos alegran la vida.</b></span></div><a className="hero-down" href="#catalogo" aria-label="Bajar al catálogo"><ArrowDown size={22}/></a><span className="visual-credit">UNA IDEA DE MARCA · SAFARI PEZ</span></div></section>
 <div className="ticker" aria-label="Alimentos, snacks y distribución"><div className="ticker-track" aria-hidden="true">{[0,1,2,3].map(i=><span key={i}>BUENOS PLATOS <PawPrint size={19}/> BUENAS COLITAS <PawPrint size={19}/> BUENOS NEGOCIOS <PawPrint size={19}/></span>)}</div></div>
 <section id="catalogo" className="catalog section-wrap"><div className="section-heading reveal"><div><p className="eyebrow">EL CATÁLOGO</p><h2>Su próximo<br/><em>plato favorito.</em></h2></div><div className="heading-aside"><p>Explora las líneas, revisa cada formato y agrega lo que necesitas a tu selección.</p><span className="small-note">Productos ilustrativos · Sin venta ni pagos reales</span></div></div><div className="catalog-toolbar"><div className="filters" aria-label="Filtrar catálogo por categoría">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} aria-pressed={filter===f} className={filter===f?"filter active":"filter"}>{f}{f==="Todos"&&<span>{products.length}</span>}</button>)}</div><span className="results"><SlidersHorizontal size={15}/><span aria-live="polite">{products.filter(p=>filter==="Todos"||p.category===filter).length} referencias</span></span></div><div className="product-grid">{products.filter(p=>filter==="Todos"||p.category===filter).map(p=><article className={`product-card ${p.color}`} key={p.id}><button className="product-visual" onClick={()=>setDetail(p)} aria-label={`Ver ficha de ${p.name}`}><span className="product-category">{p.category}</span><img src={p.image} alt={`Envase conceptual de ${p.line.toLowerCase()}`} width="1254" height="1254" loading="lazy"/><span className="view-product">Ver producto <ArrowRight size={16}/></span></button><div className="product-info"><p className="product-line">{p.line}</p><h3>{p.name}</h3><div className="product-bottom"><span className="product-weight">{p.weight}</span><button className={selection[p.id]?"add-button has-items":"add-button"} onClick={()=>add(p)} aria-label={`Agregar ${p.name} a la selección`}>{selection[p.id]?<Check size={15}/>:<Plus size={15}/>} {selection[p.id]?`Agregado · ${selection[p.id]}`:"Agregar"}</button></div></div></article>)}</div><div className="catalog-footer"><span><Package size={17}/> Elige formatos y cantidades; solicita condiciones comerciales después.</span><button className="text-button" onClick={openQuote}>Revisar mi selección <ArrowRight size={18}/></button></div></section>
 <section id="negocios" className="trade-section section-wrap"><div className="trade-photo reveal"><img src="/images/hero-pets-v2.webp" alt="Mascotas y alimento en una composición de marca Safari Pez" width="1536" height="1024" loading="lazy"/><span className="photo-label">ELLOS LO DISFRUTAN.<br/>TÚ MUEVES EL NEGOCIO.</span></div><div className="trade-copy reveal"><p className="eyebrow">PARA PETSHOPS, VETERINARIAS Y COMERCIOS</p><h2>Un buen surtido.<br/><em>Una mejor rutina.</em></h2><p>Un catálogo mayorista debe ayudarte a elegir, comparar formatos y preparar una consulta sin perderte entre mensajes.</p><ol className="trade-steps"><li><span>01</span><div><h3>Encuentra tu línea</h3><p>Filtra por perros, gatos o snacks.</p></div></li><li><span>02</span><div><h3>Arma tu selección</h3><p>Revisa las fichas y ajusta las cantidades.</p></div></li><li><span>03</span><div><h3>Prepara la consulta</h3><p>Reúne todo en un mensaje listo para compartir.</p></div></li></ol><button className="button button-dark" onClick={openQuote}>Armar mi solicitud <ArrowRight size={18}/></button></div></section>
 <section id="nosotros" className="manifesto section-wrap reveal"><span className="manifesto-kicker">LA IDEA DETRÁS DE SAFARI PEZ</span><h2>Lo que les hace bien,<br/>también debe <em>verse bien.</em></h2><div className="manifesto-bottom"><PawPrint size={54} strokeWidth={1.3}/><p>Una identidad cercana para el mundo animal.<br/>Una experiencia clara para quienes lo abastecen.</p><a href="#catalogo" className="round-link" aria-label="Volver al catálogo"><ArrowRight size={27}/></a></div></section>
 <section className="contact-section section-wrap"><div><p className="eyebrow">DE LA DEMO A TU NEGOCIO</p><h2>¿Tu catálogo podría<br/>sentirse <em>así?</em></h2><p>Esta es una propuesta de marca y desarrollo web. Podemos adaptar la identidad, los productos y la forma de cotizar a tu negocio.</p></div><a className="button button-lime" href="https://wa.me/56945857340?text=Hola%20Nicol%C3%A1s%2C%20vi%20Safari%20Pez%20y%20quiero%20conversar%20sobre%20una%20web%20para%20mi%20negocio." target="_blank" rel="noopener noreferrer">Conversar con Nicolás <ArrowRight size={20}/></a></section>
 </main><footer className="site-footer"><a href="#inicio" className="footer-brand">safari.pez</a><p>Concepto de distribuidora · Productos e imágenes ilustrativos.<br/>No se realizan ventas, reservas ni cobros.</p><a href="https://nicolas-cortez.vercel.app">Diseño + desarrollo / Nicolás Cortez <ArrowRight size={14}/></a></footer>
 <div className={notice?"toast visible":"toast"} role="status" aria-live="polite">{notice&&<><Check size={17}/>{notice}</>}</div>
 <dialog ref={detailRef} className="product-dialog" onClose={()=>setDetail(null)} onClick={e=>{if(e.target===e.currentTarget)setDetail(null)}} aria-labelledby="product-dialog-title">{detail&&<><button className="dialog-close" onClick={()=>setDetail(null)} aria-label="Cerrar ficha"><X size={22}/></button><div className={`detail-image ${detail.color}`}><img src={detail.image} alt={`Envase conceptual de ${detail.line.toLowerCase()}`} width="1254" height="1254"/></div><div className="detail-copy"><p className="eyebrow">{detail.category} · {detail.weight}</p><h2 id="product-dialog-title">{detail.name}</h2><p className="detail-line">{detail.line}</p><p>{detail.note}</p><details><summary>Sobre esta referencia</summary><p>Producto de ejemplo. Composición, disponibilidad y condiciones comerciales deben confirmarse en una implementación real.</p></details><div className="detail-actions"><button className="button button-dark" onClick={()=>add(detail)}><Plus size={18}/> Agregar a mi selección</button><button className="text-button" onClick={openQuote}>Ver selección <ArrowRight size={16}/></button></div><span className="small-note">Envase conceptual · Disponibilidad y precios no publicados</span></div></>}</dialog>
 <dialog ref={quoteRef} className="quote-dialog" onClose={()=>setQuoteOpen(false)} onClick={e=>{if(e.target===e.currentTarget)setQuoteOpen(false)}} aria-labelledby="quote-dialog-title"><div className="quote-header"><div><p className="eyebrow">TU SOLICITUD</p><h2 id="quote-dialog-title">Mi selección<span> · {count}</span></h2></div><button className="dialog-close" onClick={()=>setQuoteOpen(false)} aria-label="Cerrar selección"><X size={22}/></button></div>{!selected.length?<div className="empty-selection"><ShoppingBag size={44} strokeWidth={1.3}/><h3>Un buen plato empieza aquí.</h3><p>Agrega una referencia del catálogo para preparar una solicitud.</p><button className="button button-dark" onClick={()=>{setQuoteOpen(false);document.getElementById("catalogo")?.scrollIntoView({behavior:"smooth"})}}>Explorar el catálogo <ArrowRight size={18}/></button></div>:<><div className="selection-items">{selected.map(p=><div className="selection-item" key={p.id}><img src={p.image} alt="" width="80" height="80"/><div className="selection-item-copy"><h3>{p.name}</h3><span>{p.weight}</span></div><div className="quantity-controls"><button onClick={()=>quantity(p.id,-1)} aria-label={`Reducir cantidad de ${p.name}`}><Minus size={15}/></button><output aria-label={`Cantidad de ${p.name}`}>{selection[p.id]}</output><button disabled={selection[p.id]>=99} onClick={()=>quantity(p.id,1)} aria-label={`Aumentar cantidad de ${p.name}`}><Plus size={15}/></button></div></div>)}</div><form onSubmit={prepare} className="quote-form"><p>Completa estos datos para probar cómo se prepara una solicitud.</p><div className="form-row"><label>Tu nombre<input name="name" required maxLength={80} autoComplete="name" placeholder="Nombre y apellido" onChange={()=>setRequest("")}/></label><label>Tu negocio<input name="business" required maxLength={100} autoComplete="organization" placeholder="Nombre de tu negocio" onChange={()=>setRequest("")}/></label></div><label>Comuna<input name="city" required maxLength={80} autoComplete="address-level2" placeholder="¿Dónde está tu negocio?" onChange={()=>setRequest("")}/></label><button className="button button-dark" type="submit">Preparar solicitud <ArrowRight size={18}/></button><p className="small-note">Demo local: estos datos no se envían al preparar la solicitud. WhatsApp abre una consulta con Nicolás sobre desarrollo web.</p></form>{request&&<section className="prepared-request" aria-live="polite"><h3>Tu solicitud está lista.</h3><pre>{request}</pre><div className="request-actions"><button className="button button-outline" onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?"Copiada":"Copiar solicitud"}</button><a className="button button-lime" href={`https://wa.me/56945857340?text=${encodeURIComponent(request)}`} target="_blank" rel="noopener noreferrer">Consultar esta demo <ArrowRight size={16}/></a></div></section>}</>}</dialog>
 </>;
}
