"use client";

import Image from "next/image";
import { ArrowRight, Bone, Cat, ChevronRight, Clock3, Dog, HeartPulse, MapPin, PackageCheck, PawPrint, ShieldCheck, Truck } from "lucide-react";

const benefits = [
  { icon: ShieldCheck, title: "Marcas que dan confianza", text: "Un catálogo seleccionado para cada etapa y necesidad." },
  { icon: Truck, title: "Despacho que cumple", text: "Preparación ordenada y entregas coordinadas para tu negocio." },
  { icon: HeartPulse, title: "Asesoría cercana", text: "Te ayudamos a elegir la línea correcta para tus clientes." },
  { icon: PackageCheck, title: "Stock para crecer", text: "Disponibilidad y reposición pensadas para una buena operación." },
];
const categories = [
  { icon: Dog, name: "Perros", description: "Nutrición diaria, premium y especializada.", color: "bg-[#d9e6dc]" },
  { icon: Cat, name: "Gatos", description: "Fórmulas de sabor, bienestar y vitalidad.", color: "bg-[#f6d7ba]" },
  { icon: Bone, name: "Snacks & premios", description: "Pequeños momentos para consentirlos.", color: "bg-[#f3e7b7]" },
  { icon: HeartPulse, name: "Línea veterinaria", description: "Opciones de cuidado para necesidades especiales.", color: "bg-[#d9e6ec]" },
];

export default function Home() {
  return <main>
    <nav className="nav"><a className="brand" href="#inicio" aria-label="Alimentos para mascotas, inicio"><span className="brand-mark"><PawPrint size={19}/></span><span>ALIMENTOS<br/><b>PARA MASCOTAS</b></span></a><div className="nav-links"><a href="#nosotros">Nosotros</a><a href="#catalogo">Catálogo</a><a href="#negocio">Para tu negocio</a><a href="#contacto">Contacto</a></div><a className="nav-cta" href="#contacto">Cotizar <ArrowRight size={16}/></a></nav>
    <section id="inicio" className="hero section-pad"><div className="hero-copy"><p className="eyebrow"><span/> DISTRIBUIDORA ESPECIALIZADA</p><h1>Alimentos para<br/><em>mascotas.</em></h1><p className="lead">Un catálogo profesional de nutrición animal, con atención cercana y una logística que acompaña a petshops, veterinarias y comercios.</p><div className="hero-actions"><a className="btn btn-primary" href="#catalogo">Ver categorías <ArrowRight size={18}/></a><a className="text-link" href="#negocio">Soy negocio <ChevronRight size={18}/></a></div><div className="trust-row"><span className="trust-icon"><PackageCheck size={20}/></span><p><b>Atención comercial personalizada</b><br/>para armar pedidos a la medida de tu operación.</p></div></div><div className="hero-image-wrap"><Image className="hero-image" src="/images/safari-pez-hero.png" alt="Perro y gato junto a alimentos para mascotas" width={1536} height={1024} priority/><div className="floating-card"><span className="floating-icon"><PackageCheck size={19}/></span><div><b>Stock listo</b><small>para tu negocio</small></div></div></div></section>
    <section className="ticker"><span>• NUTRICIÓN CON PROPÓSITO</span><span>• LOGÍSTICA QUE ACOMPAÑA</span><span>• MARCAS QUE DAN CONFIANZA</span><span>• NUTRICIÓN CON PROPÓSITO</span></section>
    <section id="nosotros" className="section-pad intro"><div><p className="eyebrow dark"><span/> MÁS QUE DISTRIBUCIÓN</p><h2>Hacemos que el bienestar llegue a cada plato.</h2></div><p className="intro-text">En Safari Pez unimos cercanía animal y orden comercial. Somos el respaldo de quienes necesitan productos confiables, atención ágil y una relación que crece en el tiempo.</p></section>
    <section className="section-pad benefits"><div className="section-heading"><p className="eyebrow dark"><span/> NUESTRA FORMA DE TRABAJAR</p><h2>Tu operación, bien alimentada.</h2></div><div className="benefit-grid">{benefits.map(({icon: Icon,title,text},i)=><article className={`benefit b${i}`} key={title}><div className="icon-chip"><Icon size={26}/></div><h3>{title}</h3><p>{text}</p><ArrowRight className="card-arrow" size={20}/></article>)}</div></section>
    <section id="catalogo" className="catalog section-pad"><div className="catalog-top"><div><p className="eyebrow dark"><span/> EXPLORA EL CATÁLOGO</p><h2>Un mundo para<br/>mover <em>colitas.</em></h2></div><a className="btn btn-dark" href="#contacto">Solicitar catálogo <ArrowRight size={18}/></a></div><div className="category-grid">{categories.map(({icon: Icon,name,description,color})=><article className={`category ${color}`} key={name}><Icon size={44} strokeWidth={1.5}/><div><h3>{name}</h3><p>{description}</p></div><span><ArrowRight size={20}/></span></article>)}</div></section>
    <section id="negocio" className="process section-pad"><div className="process-copy"><p className="eyebrow"><span/> PARA TU NEGOCIO</p><h2>Una ruta simple.<br/>Un gran respaldo.</h2><p>Desde una tienda independiente hasta una cadena de locales: ajustamos el servicio a tu ritmo.</p><a className="btn btn-primary" href="#contacto">Conversemos <ArrowRight size={18}/></a></div><ol className="steps"><li><span>01</span><div><h3>Cuéntanos qué necesitas</h3><p>Conocemos tu negocio, público y frecuencia de compra.</p></div></li><li><span>02</span><div><h3>Armamos tu pedido</h3><p>Seleccionamos las líneas que mejor calzan contigo.</p></div></li><li><span>03</span><div><h3>Preparamos y despachamos</h3><p>Tu mercadería llega lista para seguir creciendo.</p></div></li></ol></section>
    <section className="numbers"><div><b>+10</b><span>años acompañando<br/>a negocios pet</span></div><div><b>+80</b><span>productos para<br/>cada necesidad</span></div><div><b>100%</b><span>compromiso con<br/>el bienestar animal</span></div><div><b>1</b><span>equipo para<br/>responderte</span></div></section>
    <section id="contacto" className="contact section-pad"><div><p className="eyebrow dark"><span/> HABLEMOS</p><h2>Tu próximo pedido<br/>puede empezar <em>hoy.</em></h2><p>Escríbenos y te ayudaremos a encontrar la mejor solución para tu negocio.</p><div className="contact-detail"><MapPin size={20}/><span>Atendemos comercios, veterinarias y petshops.</span></div><div className="contact-detail"><Clock3 size={20}/><span>Respuesta comercial ágil y personalizada.</span></div></div><form className="contact-form"><label>Nombre<input placeholder="¿Cómo te llamas?"/></label><label>Tipo de negocio<select defaultValue=""><option value="" disabled>Selecciona una opción</option><option>Petshop o tienda</option><option>Veterinaria</option><option>Supermercado / minimarket</option><option>Compra por volumen</option></select></label><label>WhatsApp o correo<input placeholder="Para responderte pronto"/></label><button className="btn btn-primary" type="button">Quiero cotizar <ArrowRight size={18}/></button></form></section>
    <footer><a className="brand" href="#inicio"><span className="brand-mark"><PawPrint size={19}/></span><span>ALIMENTOS<br/><b>PARA MASCOTAS</b></span></a><p>Nutrición y distribución para mascotas.</p><div><a href="#catalogo">Catálogo</a><a href="#contacto">Contacto</a><a href="#negocio">B2B</a></div></footer>
  </main>;
}
